program: test_sweep.py

method: bayes
metric:
  name: validation_acc
  goal: maximize

parameters:
  optimizer:
    values: ["adam", "sgd", "rms"]

  learning_rate:
    min: 0.00001
    max: 0.01

  batch_size:
    values: [32, 64, 128]

  hidden1:
    values: [64, 128, 256]
  hidden2:
    values: [32, 64, 128]

  dropout1:
    min: 0.0
    max: 0.4
  dropout2:
    min: 0.0
    max: 0.3

  seed:
    values: [42, 69, 1337]
